// Auto-generated by Supabase — do not edit by hand.
// Run: npx supabase gen types typescript --project-id <project-id> > src/types/database.ts

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          email: string;
          full_name: string | null;
          timezone: string;
          push_token: string | null;
          phone: string | null;
          sms_opt_in: boolean;
          notification_intensity: 'intense' | 'moderate' | 'quiet';
          quiet_hours_start: string | null;
          quiet_hours_end: string | null;
          onboarding_complete: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['users']['Row'], 'created_at' | 'updated_at'> & {
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database['public']['Tables']['users']['Insert']>;
      };
      goals: {
        Row: {
          id: string;
          user_id: string;
          title: string;
          description: string | null;
          target_date: string;
          status: 'active' | 'complete' | 'cancelled';
          goal_type: 'annual' | 'quarterly' | 'project';
          ai_breakdown_metadata: Json | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['goals']['Row'], 'id' | 'created_at' | 'updated_at'> & {
          id?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database['public']['Tables']['goals']['Insert']>;
      };
      projects: {
        Row: {
          id: string;
          user_id: string;
          goal_id: string;
          title: string;
          description: string | null;
          status: 'active' | 'complete' | 'cancelled';
          target_date: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['projects']['Row'], 'id' | 'created_at' | 'updated_at'> & {
          id?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database['public']['Tables']['projects']['Insert']>;
      };
      tasks: {
        Row: {
          id: string;
          user_id: string;
          project_id: string | null;
          goal_id: string | null;
          title: string;
          description: string | null;
          status: 'not_started' | 'in_progress' | 'blocked' | 'complete' | 'cancelled';
          priority: 1 | 2 | 3 | 4; // 1 = highest
          due_date: string | null;
          start_date: string | null;
          estimated_minutes: number | null;
          actual_minutes: number | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['tasks']['Row'], 'id' | 'created_at' | 'updated_at'> & {
          id?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database['public']['Tables']['tasks']['Insert']>;
      };
      task_check_ins: {
        Row: {
          id: string;
          task_id: string;
          user_id: string;
          action: 'status_change' | 'snooze' | 'reschedule' | 'complete' | 'help_request' | 'note';
          previous_status: string | null;
          new_status: string | null;
          previous_due_date: string | null;
          new_due_date: string | null;
          reschedule_reason: string | null;
          note: string | null;
          created_at: string;
        };
        Insert: Omit<Database['public']['Tables']['task_check_ins']['Row'], 'id' | 'created_at'> & {
          id?: string;
          created_at?: string;
        };
        Update: never;
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
};
